# Generated by Django 4.1.5 on 2023-01-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId_text', models.CharField(max_length=200)),
                ('custName_text', models.CharField(max_length=200)),
                ('licenseId_text', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.CharField(max_length=200)),
                ('macAddress', models.CharField(max_length=200)),
                ('ioMode', models.IntegerField(default=0)),
                ('programId', models.CharField(max_length=200)),
                ('programName', models.CharField(max_length=200)),
                ('bridgeIP', models.CharField(max_length=200)),
                ('bridge', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
