# Generated by Django 4.1.5 on 2023-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='macAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
