# Generated by Django 4.1.5 on 2023-02-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_node_macaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=100)),
                ('license_in_use', models.BooleanField()),
                ('active_ind', models.BooleanField(default=True)),
                ('replay_ind', models.BooleanField(default=True)),
                ('studio_ind', models.BooleanField(default=True)),
                ('review_ind', models.BooleanField(default=True)),
                ('slomo_ind', models.BooleanField()),
                ('dante_ind', models.BooleanField()),
                ('uhd_ind', models.BooleanField()),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_in', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=32)),
                ('program_id', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('io_mode', models.CharField(max_length=10)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.license')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='custId_text',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='custName_text',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='licenseId_text',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(default='fred', max_length=100),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='license',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
    ]
