# Generated by Django 4.1.5 on 2023-02-10 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customer_cust_id_alter_customer_cust_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cust_name']},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['license_no']},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['program_name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='license',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date added'),
        ),
    ]
